### ISSUE TITLE
SWC Failed to load

### ISSUE THREAD

**Issue by C3viche** [include-davis/cohort-platform#11]
Had this issue with starting the development server (`npm run dev`) after installing dependencies (`npm i`). This [article](https://nextjs.org/docs/messages/failed-loading-swc) explains what it is.

If any of ya'll have trouble with it all I did was just delete my `node_modules` directory and `package-lock.json`
Then I ran `npm i` again.

`rm -rf node_modules && rm package-lock.json && npm i`

**Comment by JayJ104** [comment]
hey i think you should put this on slack, don't think most people get notified about github issues (atleast I don't)
