### ISSUE TITLE
ESLint and ignore .vscode

### ISSUE THREAD

**Issue by C3viche** [include-davis/cohort-platform#12]
We should probably add `.vscode` to the `.gitignore` since I assume many of us are probably using VSCode and are going to change ESLint for the workspace settings.

BTW: This is what I put in my `.vscode/settings.json`. Not sure if it's exactly correct for the workflow to pass
```
{
    "editor.codeActionsOnSave": {
     "source.fixAll.eslint": "explicit"
    },
    "eslint.validate": [
        "javascript"
    ],
    "[javascriptreact]": {
        "editor.indentSize": 2
    }
}
```

**Comment by JayJ104** [comment]
this should be fine. again, put it on slack for everyone!
