### ISSUE TITLE
homepage: workshops timeline section

### ISSUE THREAD

**Issue by JayJ104** [include-davis/cohort-platform#3]
This ticket includes the three boxes between the welcome and timeline section.

- the left half of the purple section (with the title "Technical Workshops") is sticky, i.e. should appear stationary as the user scrolls through the timeline on the right.
- Active card (atmost one at any time):
        - will have the green strip on the right sid
        - will expand to display the workshop desdcription and tags
- non-active cards will be collapsed and with the purple strip
- circles on the timeline progress line should align with the circles on the card

**Comment by C3viche** [comment]
I gotchu
